# Generated by Django 3.2 on 2021-04-10 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notebooks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PipelineStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_num', models.IntegerField(default=1)),
                ('function', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('output', models.CharField(max_length=120)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebooks.notebookmodel')),
                ('pipeline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipelines.pipeline')),
            ],
            options={
                'unique_together': {('pipeline_id', 'step_num')},
            },
        ),
    ]
