# Generated by Django 3.2 on 2021-04-08 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import notebooks.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotebookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbose_name', models.CharField(max_length=50)),
                ('name', models.SlugField(unique=True)),
                ('notebook_group', models.CharField(default='Test_Group', max_length=50)),
                ('notebook', models.FileField(upload_to=notebooks.models.generate_filename)),
                ('notebook_html', models.TextField()),
                ('notebook_test', models.FileField(upload_to=notebooks.models.generate_filename)),
                ('notebook_test_html', models.TextField()),
                ('description', models.CharField(max_length=120, null=True)),
                ('functions', jsonfield.fields.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
